[project]
name = "tictactoe"
version = "1.0"
description = "Monte Carlo Search and Monte Carlo Tree Search on a game of TicTacToe"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
]
